version: '3'

services:
  nifi:
    image: apache/nifi:2.4.0
    ports:
      - "8443:8443"
      - "3306:3306"
      - "3307:3307"
    volumes:
      - ./custom-nars:/opt/nifi/custom-nars
      - C:\Users\arnab.moitra\Desktop\NIFI_Tests\nifi_input:/opt/nifi/input
      - C:\Users\arnab.moitra\Desktop\NIFI_Tests\nifi_output:/opt/nifi/output
      - C:\Users\arnab.moitra\Desktop\klab-nifi\nifi-klab-nifi\src\main\python:/opt/nifi/py_scripts
      #      - C:\Users\arnab.moitra\Desktop\klab-integration.cert:/home/nifi/.klab/klab.cert
      - C:\Users\arnab.moitra\.klab:/home/nifi/.klab

    entrypoint: >
      bash -c "
        echo 'Copying custom NARs to lib...' &&
        cp /opt/nifi/custom-nars/*.nar /opt/nifi/nifi-current/lib/ &&
        cp -r /opt/nifi/py_scripts/* /opt/nifi/nifi-current/python_extensions/ &&
        echo 'Starting NiFi...' &&
        /opt/nifi/scripts/start.sh
      "
      
